/**
 * Términos y condiciones de Chess Fortune.
 * ES: texto íntegro de chessfortune.com/terms&cond (versión que prevalece, ver 1.2).
 * EN: traducción de buena fe del original en español.
 */

type Item = { n: string; t: string; p: string; list?: string[] };
type Section = { id: string; title: string; intro?: string; items: Item[] };
export type Terms = { important: string; intro: string; tocTitle: string; sections: Section[] };

const es: Terms = {
  important: 'IMPORTANTE',
  tocTitle: 'Contenido',
  intro:
    'Antes de proceder al registro del usuario usted debe leer atentamente estos términos y condiciones. Chessfortune.com, en lo sucesivo denominada “CHESSFORTUNE.COM” es una plataforma digital que ofrece la experiencia de intercambio entre jugadores de ajedrez con la posibilidad de obtener recompensas. Estos términos están sujetos a posibles cambios sin previo aviso. Todo el contenido y materiales distribuidos de este sitio web son propiedad o licencia de CHESSFORTUNE.COM y los otorgantes de licencias retienen los derechos de propiedad intelectual, incluyendo, pero no limitado a los contenidos, imágenes, marcas registradas y otros derechos especiales de cualquier nombre. Al registrarse para hacer uso de los servicios contenidos en este acuerdo, el usuario está certificando que es mayor de 17 años o que ha cumplido la mayoría de edad en caso de que el territorio donde se encuentre el usuario establezca un límite de edad superior al de diecisiete (17) años para poder realizar transacciones, y que acepta los siguientes términos y condiciones:',
  sections: [
    {
      id: 'condiciones-generales',
      title: '1. Condiciones generales',
      items: [
        { n: '1.1', t: 'Aceptación de los términos', p: 'Al acceder y utilizar nuestro sitio web, el usuario acepta cumplir con estos términos y condiciones en su totalidad. Si no está de acuerdo con alguno de los términos, no debe utilizar CHESSFORTUNE.COM. Asimismo, una vez publicadas en CHESSFORTUNE.COM las modificaciones futuras se entenderán aceptadas por el usuario que no elimine su cuenta en el lapso de las 48 horas siguientes a la publicación de la modificación de estos términos y condiciones.' },
        { n: '1.2', t: 'Lenguaje preferente', p: 'Todos los términos, reglas y políticas publicados en CHESSFORTUNE.COM, utilizan el español como el lenguaje preferente. Las traducciones a otros idiomas se presumen realizadas de buena fe como reproducción del original en español. Sin embargo, en caso de que surja alguna duda con respecto a la interpretación de los términos y condiciones, entre la versión en español y una traducción, la versión en español tendrá prioridad sobre cualquier traducción.' },
        { n: '1.3', t: 'Modificaciones de los términos', p: 'CHESSFORTUNE.COM podría modificar estos términos y condiciones en cualquier momento. Las modificaciones entrarán en vigor tan pronto como se publiquen en este sitio web. Es responsabilidad del usuario revisar regularmente la sección de términos y condiciones para mantenerse actualizado.' },
        { n: '1.4', t: 'Legalidad de la suscripción', p: 'Antes de registrarse, el usuario deberá comprobar que las leyes en el estado/país donde resida, transite o utilice la aplicación para realizar las transacciones no prohíban las transacciones con criptomonedas en línea, debido a que las operaciones con criptomonedas en línea pueden ser ilegales en la jurisdicción o país donde resida, transite o utilice la aplicación el usuario; en cuyo caso, el usuario será el único responsable por la infracción de la normativa que le resulte aplicable, dejando libre de cualquier responsabilidad a CHESSFORTUNE.COM, pues con el registro del usuario se entiende que el usuario ha leído la presente información y ha verificado previamente que la legislación que le resulta aplicable no prohíbe las operaciones con criptomonedas en línea. Asimismo, el usuario declara conocer que CHESSFORTUNE.COM está destinado únicamente a personas mayores de edad y en jurisdicciones donde el juego en línea sea legal. Al acceder y utilizar CHESSFORTUNE.COM, el cliente confirma que cumple con los requisitos de edad y que está en una jurisdicción donde el uso de CHESSFORTUNE.COM es legal. Por lo tanto, CHESSFORTUNE.COM se reserva el derecho de banear usuarios cuya actividad se detecte como realizada en ubicaciones donde las operaciones con criptomonedas en línea estén prohibidas, y en caso de considerarlo necesario, CHESSFORTUNE.COM puede solicitar a documentación adicional para garantizar la seguridad y la prevención del fraude. El hecho de que CHESSFORTUNE.COM esté disponible países o regiones donde estén prohibidas las operaciones con criptomonedas online, o que se muestre en el idioma oficial de cualquiera de esos países, no puede interpretarse como justificación de la legalidad del uso de CHESSFORTUNE.COM o de los depósitos o retirada de fondos ganados, ni como incitación o invitación para el uso de juegos de azar en cualquier jurisdicción en la que dicha actividad esté prohibida por la ley.' },
        { n: '1.5', t: 'Responsabilidad de confidencialidad por parte del usuario', p: 'El usuario es responsable de mantener la confidencialidad de su cuenta y de todas las actividades que ocurran bajo su nombre de usuario. Debe asegurarse de que la información proporcionada durante el registro sea precisa, veraz y actualizada y será el único responsable de las consecuencias que se deriven de haber suministrado información falsa, tergiversada o inexacta.' },
        { n: '1.6', t: 'Uso del contenido', p: 'Todo el contenido de CHESSFORTUNE.COM, incluyendo textos, gráficos, logotipos, imágenes, videos, software y cualquier otro material, está protegido por derechos de autor y otros derechos de propiedad intelectual. No está permitido utilizar, copiar, modificar, distribuir o crear nuevo contenido basado en estos materiales.' },
        { n: '1.7', t: 'Depósitos y retiros', p: 'Los métodos de depósito y retiro disponibles están sujetos a términos y condiciones adicionales, establecidas por los procesadores de pago y los proveedores de servicios de pasarelas de pago incluyendo requisitos de verificación de identidad, cuyo cumplimiento estará a cargo del usuario.' },
        { n: '1.8', t: 'Exención de responsabilidad', p: 'CHESSFORTUNE.COM no se hace responsable de los daños directos, indirectos, materiales y/o morales, incidentales o consecuentes que puedan surgir del uso de este sitio web, incluyendo la pérdida de ganancias, interrupción del negocio o pérdida de datos.' },
        { n: '1.9', t: 'Límite de edad', p: 'Todos los solicitantes deben tener más de diecisiete (17) años, o haber cumplido la mayoría de edad en caso de que el territorio donde se encuentre el usuario establezca un límite de edad superior al de diecisiete (17) años para poder realizar transacciones con criptomonedas. Para registrarse en CHESSFORTUNE.COM. La plataforma está en el derecho de solicitar documentos de identidad oficiales a cualquier usuario y estará habilitada para suspender la cuenta hasta después de recibida y verificada dicha documentación, si resulta ser fraudulenta.' },
        { n: '1.10', t: 'Declaración de salud mental', p: 'Al aceptar estos términos y condiciones, el usuario confirma que no tiene adicción al juego.' },
      ],
    },
    {
      id: 'cuentas',
      title: '2. Cuentas',
      items: [
        { n: '2.1', t: 'Información de la cuenta', p: 'Toda la información proporcionada para registrarse en CHESSFORTUNE.COM debe ser veraz, completa y exacta en todos los aspectos. El usuario declara y acepta que CHESSFORTUNE.COM almacenará datos básicos como correo electrónico, nombres, apellidos, número de documento e identidad, foto de perfil, teléfono de contacto, así como también almacena datos de pagos y pasarelas de pago pertenecientes al usuario, montos aportados, retiros y depósitos. CHESSFORTUNE.COM se reserva el derecho de iniciar un procedimiento de verificación en cualquier momento, poniéndose en contacto con el cliente a través de correo electrónico, solicitando documentación de respaldo, tales como, pero no limitado a: documento de identidad, licencia de conducir, pasaporte, frente y dorso de tarjetas de crédito o débito (cuando aplique), documentos que demuestren el domicilio. Esa data solo tendrá fines operativos para CHESSFORTUNE.COM, y se resumirá que la cuenta pertenece a la persona que se registre como titular; por lo tanto, la información suministrada para el registro debería corresponder a esta persona, y CHESSFORTUNE.COM no será responsable por el uso indebido de información personal suministrada por terceros no titulares de los documentos empleados para registrar una cuenta, pues todas las cuentas se presumen abiertas de buena fe, salvo prueba en contrario.' },
        { n: '2.2', t: 'Singularidad de la cuenta', p: 'Cada usuario puede registrarse válidamente una sola vez con una única cuenta. En caso de que se detecte el registro de varias cuentas por parte de un mismo usuario, CHESSFORTUNE.COM se reserva el derecho a suspenderlas todas y retener la totalidad de los saldos acreditados, como penalización por el incumplimiento de esta condición.' },
        { n: '2.3', t: 'Carácter intransferible', p: 'Las cuentas no pueden ser transferidas, vendidas o aprovechadas por un tercero. En caso de sospecha de incumplimiento de esta condición, todas las cuentas implicadas serán puestas en suspensión temporal para determinar si hubo o no infracción de esta prohibición.' },
        { n: '2.4', t: 'Verificación de la cuenta vía e-mail', p: 'El usuario declara conocer que ciertas operaciones de su cuenta pueden requerir confirmación vía mail, para autenticar la identidad del usuario.' },
        { n: '2.5', t: 'Inactividad de la cuenta', p: 'El usuario declara conocer que la plataforma de CHESSFORTUNE.COM no tiene el propósito de fungir como wallet ni casa de cambio, por lo cual se compromete a mantener actividad regular de juego. Por lo tanto, si transcurridos noventa (90) días continuos desde la última partida, la cuenta no muestra actividad, será considerada inactiva, y CHESSFORTUNE.COM hará la advertencia al usuario para que reactive su cuenta jugando al menos una partida o retire su saldo para cerrarla definitivamente dentro del plazo de ciento ochenta (180) días continuos. Luego de este plazo, si el usuario no procede a reactivar la cuenta o a retirar los fondos disponibles para jugar, CHESSFORTUNE.COM notificará al titular de la cuenta su saldo disponible para que proceda a retirarlo dentro del plazo de treinta (30) días. Transcurrido ese último plazo sin que el usuario retire los fondos o reactive su cuenta jugando una partida, se presumirá que ha renunciado a su cuenta y los fondos que se encuentren acreditados en esa cuenta quedarán en beneficio de CHESSFORTUNE.COM. Y en caso de que la cuenta se encuentre inactiva y no tenga saldo disponible se procederá a cerrarla definitivamente transcurridos noventa (90) días contados a partir de la última partida.' },
        { n: '2.6', t: 'Suspensión de la cuenta', p: 'CHESSFORTUNE.COM se reserva el derecho a suspender una cuenta en forma temporal o definitiva, ante cualquier sospecha de incumplimiento de estos términos y condiciones, de acuerdo con el régimen disciplinario de CHESSFORTUNE.COM.' },
      ],
    },
    {
      id: 'saldo-retiros-comisiones',
      title: '3. Acreditación de saldo, retiros y comisiones',
      items: [
        { n: '3.1', t: 'Formas de depósito en CHESSFORTUNE.COM', p: 'El usuario podrá emplear métodos de pago electrónicos como criptomonedas o depósitos bancarios para adquirir la moneda seed empleada para todas las operaciones realizadas en CHESSFORTUNE.COM, y será a su vez responsable de cumplir con los términos y condiciones que les establezcan esas plataformas para el uso de las mismas. Por lo tanto, Chessfortune.com no se hace responsable por los incumplimientos de los usuarios con respecto a los términos y condiciones de las plataformas seleccionadas por el usuario para el manejo de sus fondos.' },
        { n: '3.2', t: 'Acreditación de saldo', p: 'CHESSFORTUNE.COM pone a disposición de sus usuarios diferentes métodos para ingresar fondos a sus cuentas para adquirir la moneda interna denominada seed. Cada seed tendrá un valor nominal equivalente a un dólar de los Estados Unidos de América (1 USD), los cuales podrán ser adquiridos mediante saldo de criptomonedas en Coinpayments.net o mediante depósitos bancarios. Los fondos serán acreditados en la moneda seed y todas las transacciones se llevarán a cabo en seeds y esa misma moneda se usará para acreditar las ganancias generadas.' },
        { n: '3.3', t: 'Comisiones', p: 'CHESSFORTUNE.COM no cobra comisiones por concepto de depósitos, ni tampoco cobra comisiones por concepto de retiros (quedando a salvo las comisiones que cobre la pasarela de pago seleccionada por el usuario); solamente obtiene una comisión de un dólar americano (1 USD) por el uso de la sala en cada partida, monto que se cobra al entrar a la sala.' },
        { n: '3.4', t: 'Retiros', p: 'Los retiros de fondos serán efectivos en un máximo de treinta y seis (36) horas hábiles en caso de que el usuario emplee el método de pago denominado criptomonedas y 72 horas hábiles para los retiros bancarios. CHESSFORTUNE.COM no asume comisiones de retiro por los usuarios. Cada usuario se hace responsable del monto que retira y de los costos de las plataformas que usa para administrar su dinero. El usuario declara conocer que CHESSFORTUNE.COM no es casa de cambio, por lo cual las transacciones dentro de la plataforma se realizan a través de la moneda interna denominada seed, cuyo valor estable es de un dólar americano (1 USD), motivo por el cual al registrarse y aceptar estos términos y condiciones, los usuarios declaran conocer que sus retiros solo podrán ser realizados por el monto equivalente a los seed que esté retirando, mediante retiro bancario o la criptomoneda denominada USDT.' },
        { n: '3.5', t: 'Declaración de origen y destino de los fondos', p: 'El usuario al crear una cuenta en CHESSFORTUNE.COM declara que los fondos depositados tienen un origen lícito y que el destino de los fondos también será lícito, por lo cual CHESSFORTUNE.COM se reserva el derecho de suspender temporalmente o eliminar de manera definitiva aquellas cuentas que tengan patrones sospechosos de financiamiento de actividades ilícitas.' },
      ],
    },
    {
      id: 'regimen-disciplinario',
      title: '4. Régimen disciplinario',
      intro: 'Para garantizar la transparencia y el orden en el desarrollo de las actividades de CHESSFORTUNE.COM, se establece un régimen disciplinario aplicable a cualquier incumplimiento de los términos y condiciones antes transcritos así como también a las prohibiciones expresamente determinadas en esta sección.',
      items: [
        { n: '4.1', t: 'Prohibiciones', p: 'No estará permitido:', list: [
          'El registro de nombres de usuario ofensivos, infamantes, obscenos, ya sea de manera directa o mediante caracteres intercambiados que permitan deducir el carácter nocivo del nombre.',
          'Conductas antideportivas tales como: amenazas, insultos, ofensas, denuncias infundadas y conductas similares.',
          'Uso de motores de ajedrez, software o cualquier elemento independiente del jugador que le dé ventaja injusta durante las partidas.',
        ] },
        { n: '4.2', t: 'Graduación de faltas', p: 'Las faltas se dividen en: leves, graves y gravísimas, y la determinación de su gravedad será establecida por un árbitro, mediante puntuaciones siendo de uno (01) a dos (02) puntos las leves; de tres (03) puntos hasta cuatro (04) puntos las graves, y las gravísimas sumarán nueve (09) puntos. Los árbitros de CHESSFORTUNE.COM tendrán facultades amplias para determinar la gravedad de las conductas antideportivas en que pudiesen incurrir los usuarios.', list: [
          'Son ejemplos de faltas leves: conductas antideportivas leves, sin ofensas explícitas; uso de nombres de usuario inapropiados pero no ofensivos.',
          'Son ejemplos de faltas graves: conductas antideportivas con ofensas explícitas; uso de nombres de usuario inapropiados y ofensivos.',
          'Son ejemplos de faltas gravísimas: trampas realizadas usando software para ganar las partidas; la creación de varias cuentas para obtener ganancias como referidos o para evadir sanciones; la reincidencia en faltas leves o graves que sumen nueve (09) puntos.',
        ] },
        { n: '4.3', t: 'Acreditación de faltas', p: 'El puntaje de las faltas se reflejará en el perfil del jugador, y al sumar tres (03) puntos o tres (03) faltas leves se produce un ban de un mes donde el usuario tendrá acceso a sus fondos pero no a jugar y en caso de reincidencia se aplicará una prohibición de uso de la plataforma para jugar durante 3 meses. Si las faltas suman seis (06) puntos, se produce un ban de 3 meses donde el usuario tendrá acceso a sus fondos pero no podrá jugar y si reincide se aplica un ban permanente, generará una multa del 15% de los fondos acreditados del usuario, por concepto de daños a CHESSFORTUNE.COM. En caso de sumar nueve (09) puntos quedará deshabilitada la cuenta para jugar y para acceder a los fondos, concediéndosele un plazo de treinta (30) días para que realice el retiro del setenta y cinco por ciento (75%) de los fondos, pues el incumplimiento reiterativo de los términos y condiciones o la comisión de una falta gravísima que sume nueve (09) puntos generará una multa del 15% de los fondos acreditados del usuario, por concepto de daños a CHESSFORTUNE.COM. Los juegos denunciados serán sometidos a revisión por un árbitro, quien tendrá a su disposición software especial para determinar, en el histórico de ese juego, si hubo trampa o no.' },
        { n: '4.4', t: 'Reconsideración de faltas', p: 'Los usuarios tendrán un plazo de cuarenta y cinco (45) días hábiles para solicitar ante el soporte técnico la reconsideración de la sanción impuesta por el árbitro de CHESSFORTUNE.COM y deberá esperar la resolución de la controversia durante el lapso de cuarenta y cinco (45) días hábiles dentro de los cuales se deberá producir la respuesta que confirme, modifique o revoque la sanción.' },
      ],
    },
    {
      id: 'referidos',
      title: '5. Sistema de referidos',
      intro: 'Todo usuario registrado, una vez que sea completado satisfactoriamente el proceso de registro en la plataforma de CHESSFORTUNE.COM, generará automáticamente un link de referido con el cual podrá invitar a otras personas a registrarse, y por cada usuario registrado satisfactoriamente que haya hecho su primer depósito, recibirá un (01) seed acreditado en su balance.',
      items: [],
    },
    {
      id: 'soporte-tecnico',
      title: '6. Soporte técnico',
      intro: 'El usuario podrá hacer uso dentro de CHESSFORTUNE.COM de un sistema de reportes y tickets para los usuarios, referidos a depósitos, retiros, bugs y comentarios generales. Todo ticket quedará en manos de la administración y se resolverá desde allí, manteniendo contacto con el usuario a través de la plataforma, y el usuario se compromete a hacer uso responsable del servicio de soporte técnico.',
      items: [
        { n: '6.1', t: 'Resolución de conflictos', p: 'Los usuarios tendrán un plazo de cuarenta y cinco (45) días hábiles desde que se presente alguna situación que amerite la intervención de la administración de CHESSFORTUNE.COM para manifestar ante el soporte técnico la situación y deberá esperar la respuesta durante el lapso de cuarenta y cinco (45) días hábiles dentro de los cuales se deberá producir la respuesta a su requerimiento, quedando expresamente entendido que no podrá emprenderse ninguna acción judicial o administrativa mientras esté pendiente la resolución del requerimiento realizado por el usuario.' },
        { n: '6.2', t: 'Mediación obligatoria', p: 'Antes de emprender cualquier acción de naturaleza judicial o administrativa contra CHESSFORTUNE.COM, los usuarios se comprometen a agotar la mediación con la administración de CHESSFORTUNE.COM como mecanismo alternativo de resolución de conflictos, durante el plazo de ciento ochenta (180) días contados a partir de la ocurrencia de cualquier situación que lo amerite.' },
      ],
    },
  ],
};

const en: Terms = {
  important: 'IMPORTANT',
  tocTitle: 'Contents',
  intro:
    'Before registering as a user, you must carefully read these terms and conditions. Chessfortune.com, hereinafter “CHESSFORTUNE.COM”, is a digital platform that offers chess players the experience of playing one another with the possibility of earning rewards. These terms are subject to change without prior notice. All content and materials distributed on this website are owned by or licensed to CHESSFORTUNE.COM, and the licensors retain the intellectual property rights, including but not limited to content, images, trademarks and other special rights of any kind. By registering to use the services covered by this agreement, the user certifies that they are over 17 years of age, or have reached the age of majority where the territory in which the user is located sets an age limit higher than seventeen (17) for carrying out transactions, and that they accept the following terms and conditions:',
  sections: [
    {
      id: 'condiciones-generales',
      title: '1. General conditions',
      items: [
        { n: '1.1', t: 'Acceptance of the terms', p: 'By accessing and using our website, the user agrees to comply with these terms and conditions in full. If you do not agree with any of the terms, you must not use CHESSFORTUNE.COM. Likewise, once published on CHESSFORTUNE.COM, future amendments shall be deemed accepted by any user who does not delete their account within 48 hours of the publication of the amendment to these terms and conditions.' },
        { n: '1.2', t: 'Preferred language', p: 'All terms, rules and policies published on CHESSFORTUNE.COM use Spanish as the preferred language. Translations into other languages are presumed to have been made in good faith as a reproduction of the Spanish original. However, should any doubt arise regarding the interpretation of the terms and conditions between the Spanish version and a translation, the Spanish version shall prevail over any translation.' },
        { n: '1.3', t: 'Amendments to the terms', p: 'CHESSFORTUNE.COM may amend these terms and conditions at any time. Amendments take effect as soon as they are published on this website. It is the user’s responsibility to review the terms and conditions section regularly to stay up to date.' },
        { n: '1.4', t: 'Legality of registration', p: 'Before registering, the user must check that the laws of the state/country in which they reside, are travelling through or use the application to carry out transactions do not prohibit online cryptocurrency transactions, since online cryptocurrency operations may be illegal in the jurisdiction or country in which the user resides, is travelling through or uses the application; in that case, the user shall be solely responsible for breaching the regulations applicable to them, releasing CHESSFORTUNE.COM from any liability, since by registering the user is understood to have read this information and to have previously verified that the legislation applicable to them does not prohibit online cryptocurrency operations. The user also declares that they are aware that CHESSFORTUNE.COM is intended solely for adults and for jurisdictions where online gaming is legal. By accessing and using CHESSFORTUNE.COM, the customer confirms that they meet the age requirements and are in a jurisdiction where the use of CHESSFORTUNE.COM is legal. Accordingly, CHESSFORTUNE.COM reserves the right to ban users whose activity is detected as taking place in locations where online cryptocurrency operations are prohibited and, where it deems necessary, CHESSFORTUNE.COM may request additional documentation to ensure security and prevent fraud. The fact that CHESSFORTUNE.COM is available in countries or regions where online cryptocurrency operations are prohibited, or is displayed in the official language of any of those countries, cannot be interpreted as justification of the legality of using CHESSFORTUNE.COM or of depositing or withdrawing winnings, nor as an incitement or invitation to engage in gambling in any jurisdiction where such activity is prohibited by law.' },
        { n: '1.5', t: 'User confidentiality responsibility', p: 'The user is responsible for keeping their account confidential and for all activity that takes place under their username. They must ensure that the information provided during registration is accurate, truthful and up to date, and shall be solely responsible for the consequences of having provided false, misrepresented or inaccurate information.' },
        { n: '1.6', t: 'Use of content', p: 'All content on CHESSFORTUNE.COM, including text, graphics, logos, images, videos, software and any other material, is protected by copyright and other intellectual property rights. Using, copying, modifying, distributing or creating new content based on these materials is not permitted.' },
        { n: '1.7', t: 'Deposits and withdrawals', p: 'The available deposit and withdrawal methods are subject to additional terms and conditions set by payment processors and payment gateway service providers, including identity verification requirements, compliance with which is the user’s responsibility.' },
        { n: '1.8', t: 'Disclaimer', p: 'CHESSFORTUNE.COM is not liable for any direct, indirect, material and/or moral, incidental or consequential damages that may arise from the use of this website, including loss of profits, business interruption or loss of data.' },
        { n: '1.9', t: 'Age limit', p: 'All applicants must be over seventeen (17) years of age, or have reached the age of majority where the territory in which the user is located sets an age limit higher than seventeen (17) for carrying out cryptocurrency transactions, in order to register on CHESSFORTUNE.COM. The platform is entitled to request official identity documents from any user and may suspend the account until such documentation has been received and verified, if it proves to be fraudulent.' },
        { n: '1.10', t: 'Mental health statement', p: 'By accepting these terms and conditions, the user confirms that they do not have a gambling addiction.' },
      ],
    },
    {
      id: 'cuentas',
      title: '2. Accounts',
      items: [
        { n: '2.1', t: 'Account information', p: 'All information provided to register on CHESSFORTUNE.COM must be truthful, complete and accurate in every respect. The user declares and accepts that CHESSFORTUNE.COM will store basic data such as email address, first names, surnames, identity document number, profile photo and contact telephone number, as well as the user’s payment data and payment gateways, amounts contributed, withdrawals and deposits. CHESSFORTUNE.COM reserves the right to start a verification procedure at any time by contacting the customer by email and requesting supporting documentation such as, but not limited to: identity document, driving licence, passport, front and back of credit or debit cards (where applicable) and documents proving the address. This data shall be used for CHESSFORTUNE.COM’s operational purposes only, and the account shall be presumed to belong to the person registered as its holder; therefore, the information provided for registration should correspond to that person, and CHESSFORTUNE.COM shall not be liable for the misuse of personal information supplied by third parties who are not the holders of the documents used to register an account, as all accounts are presumed to have been opened in good faith unless proven otherwise.' },
        { n: '2.2', t: 'Single account', p: 'Each user may validly register only once, with a single account. If multiple accounts are detected as registered by the same user, CHESSFORTUNE.COM reserves the right to suspend all of them and withhold all credited balances as a penalty for breaching this condition.' },
        { n: '2.3', t: 'Non-transferability', p: 'Accounts may not be transferred, sold or used by a third party. If a breach of this condition is suspected, all accounts involved will be temporarily suspended to determine whether this prohibition has been breached.' },
        { n: '2.4', t: 'Account verification by email', p: 'The user acknowledges that certain operations on their account may require confirmation by email to authenticate the user’s identity.' },
        { n: '2.5', t: 'Account inactivity', p: 'The user acknowledges that the CHESSFORTUNE.COM platform is not intended to act as a wallet or currency exchange, and therefore undertakes to maintain regular playing activity. Accordingly, if the account shows no activity for ninety (90) consecutive days after the last game, it will be considered inactive and CHESSFORTUNE.COM will warn the user to reactivate their account by playing at least one game, or to withdraw their balance and close it permanently, within one hundred and eighty (180) consecutive days. After this period, if the user has not reactivated the account or withdrawn the funds available for play, CHESSFORTUNE.COM will notify the account holder of their available balance so that they can withdraw it within thirty (30) days. Once that final period has elapsed without the user withdrawing the funds or reactivating their account by playing a game, the user shall be presumed to have abandoned their account, and the funds credited to that account shall accrue to CHESSFORTUNE.COM. If the account is inactive and has no available balance, it will be permanently closed ninety (90) days after the last game.' },
        { n: '2.6', t: 'Account suspension', p: 'CHESSFORTUNE.COM reserves the right to suspend an account temporarily or permanently on any suspicion of a breach of these terms and conditions, in accordance with CHESSFORTUNE.COM’s disciplinary rules.' },
      ],
    },
    {
      id: 'saldo-retiros-comisiones',
      title: '3. Balance, withdrawals and fees',
      items: [
        { n: '3.1', t: 'Deposit methods on CHESSFORTUNE.COM', p: 'The user may use electronic payment methods such as cryptocurrencies or bank deposits to acquire the seed currency used for all operations on CHESSFORTUNE.COM, and shall in turn be responsible for complying with the terms and conditions set by those platforms for their use. Therefore, Chessfortune.com is not responsible for users’ breaches of the terms and conditions of the platforms they choose to manage their funds.' },
        { n: '3.2', t: 'Crediting of balance', p: 'CHESSFORTUNE.COM offers its users different methods for adding funds to their accounts in order to acquire the internal currency called seed. Each seed has a nominal value equivalent to one United States dollar (1 USD) and may be acquired using a cryptocurrency balance on Coinpayments.net or by bank deposit. Funds will be credited in seeds, all transactions will be carried out in seeds, and that same currency will be used to credit any winnings.' },
        { n: '3.3', t: 'Fees', p: 'CHESSFORTUNE.COM does not charge fees for deposits or for withdrawals (without prejudice to any fees charged by the payment gateway chosen by the user); it only earns a fee of one US dollar (1 USD) for the use of the room in each game, charged on entering the room.' },
        { n: '3.4', t: 'Withdrawals', p: 'Withdrawals will be completed within a maximum of thirty-six (36) business hours when the user uses the cryptocurrency payment method, and 72 business hours for bank withdrawals. CHESSFORTUNE.COM does not cover withdrawal fees on behalf of users. Each user is responsible for the amount they withdraw and for the costs of the platforms they use to manage their money. The user acknowledges that CHESSFORTUNE.COM is not a currency exchange, and that transactions within the platform are therefore made in the internal currency called seed, whose stable value is one US dollar (1 USD); for this reason, by registering and accepting these terms and conditions, users acknowledge that their withdrawals may only be made for the amount equivalent to the seeds being withdrawn, by bank withdrawal or in the cryptocurrency USDT.' },
        { n: '3.5', t: 'Declaration of source and use of funds', p: 'By creating an account on CHESSFORTUNE.COM, the user declares that the funds deposited come from a lawful source and will be used for lawful purposes, and CHESSFORTUNE.COM therefore reserves the right to temporarily suspend or permanently delete accounts showing suspicious patterns of financing illicit activities.' },
      ],
    },
    {
      id: 'regimen-disciplinario',
      title: '4. Disciplinary rules',
      intro: 'To ensure transparency and order in the activities of CHESSFORTUNE.COM, disciplinary rules are established that apply to any breach of the terms and conditions set out above, as well as to the prohibitions expressly set out in this section.',
      items: [
        { n: '4.1', t: 'Prohibitions', p: 'The following are not permitted:', list: [
          'Registering offensive, defamatory or obscene usernames, whether directly or by swapping characters in a way that still reveals the harmful nature of the name.',
          'Unsportsmanlike conduct such as threats, insults, offences, unfounded accusations and similar behaviour.',
          'Using chess engines, software or any element independent of the player that gives them an unfair advantage during games.',
        ] },
        { n: '4.2', t: 'Classification of offences', p: 'Offences are classified as minor, serious and very serious, and their severity is determined by an arbiter using points: one (01) to two (02) points for minor offences, three (03) to four (04) points for serious offences, and very serious offences count as nine (09) points. CHESSFORTUNE.COM arbiters have broad powers to determine the severity of any unsportsmanlike conduct by users.', list: [
          'Examples of minor offences: mild unsportsmanlike conduct without explicit offence; inappropriate but non-offensive usernames.',
          'Examples of serious offences: unsportsmanlike conduct with explicit offence; inappropriate and offensive usernames.',
          'Examples of very serious offences: cheating with software to win games; creating multiple accounts to earn referral rewards or to evade penalties; repeated minor or serious offences adding up to nine (09) points.',
        ] },
        { n: '4.3', t: 'Recording of offences', p: 'Offence points are shown on the player’s profile. Reaching three (03) points or three (03) minor offences results in a one-month ban, during which the user can access their funds but cannot play; a repeat offence results in a 3-month ban from playing on the platform. If offences reach six (06) points, a 3-month ban applies, during which the user can access their funds but cannot play; a repeat offence results in a permanent ban and a fine of 15% of the user’s credited funds as damages to CHESSFORTUNE.COM. Reaching nine (09) points disables the account for playing and for accessing funds, and the user is given thirty (30) days to withdraw seventy-five percent (75%) of the funds, since repeated breaches of the terms and conditions or committing a very serious offence worth nine (09) points result in a fine of 15% of the user’s credited funds as damages to CHESSFORTUNE.COM. Reported games will be reviewed by an arbiter, who will have special software to determine from that game’s history whether cheating took place.' },
        { n: '4.4', t: 'Appeal of offences', p: 'Users have forty-five (45) business days to request from technical support a reconsideration of the penalty imposed by the CHESSFORTUNE.COM arbiter, and must await the resolution of the dispute for a period of forty-five (45) business days, within which a response confirming, modifying or revoking the penalty must be issued.' },
      ],
    },
    {
      id: 'referidos',
      title: '5. Referral system',
      intro: 'Every registered user, once the registration process on the CHESSFORTUNE.COM platform has been successfully completed, automatically generates a referral link with which they can invite other people to register, and for each successfully registered user who makes their first deposit, they will receive one (01) seed credited to their balance.',
      items: [],
    },
    {
      id: 'soporte-tecnico',
      title: '6. Technical support',
      intro: 'Within CHESSFORTUNE.COM, users can use a reporting and ticket system for matters relating to deposits, withdrawals, bugs and general comments. All tickets are handled and resolved by the administration, which keeps in contact with the user through the platform, and the user undertakes to use the technical support service responsibly.',
      items: [
        { n: '6.1', t: 'Dispute resolution', p: 'Users have forty-five (45) business days from the occurrence of any situation requiring the intervention of CHESSFORTUNE.COM’s administration to report it to technical support, and must await a response for a period of forty-five (45) business days, within which a response to their request must be issued; it being expressly understood that no judicial or administrative action may be brought while the resolution of the user’s request is pending.' },
        { n: '6.2', t: 'Mandatory mediation', p: 'Before bringing any judicial or administrative action against CHESSFORTUNE.COM, users undertake to exhaust mediation with CHESSFORTUNE.COM’s administration as an alternative dispute resolution mechanism for a period of one hundred and eighty (180) days from the occurrence of any situation that warrants it.' },
      ],
    },
  ],
};

export const terms: Record<'es' | 'en', Terms> = { es, en };
